# Generated by Django 3.1 on 2020-08-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='res_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
