# Generated by Django 3.1 on 2020-08-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_res_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='res_id',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
